# Generated by Django 2.2 on 2020-04-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='名字', max_length=50, verbose_name='名字')),
                ('money', models.CharField(default='', help_text='注册资金', max_length=50, verbose_name='注册资金')),
                ('person', models.CharField(default='', help_text='注册人', max_length=50, verbose_name='注册人')),
                ('location', models.CharField(default='', help_text='注册区域', max_length=50, verbose_name='注册区域')),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
            },
        ),
    ]
