# Generated by Django 2.2 on 2020-04-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='姓名', max_length=30, verbose_name='姓名')),
                ('sex', models.CharField(default='', help_text='性别', max_length=30, verbose_name='性别')),
                ('phone', models.CharField(default='', help_text='手机号', max_length=30, verbose_name='手机号')),
                ('value', models.CharField(default='', help_text='积分值', max_length=30, verbose_name='积分值')),
            ],
            options={
                'verbose_name': '会员',
                'verbose_name_plural': '会员',
            },
        ),
    ]
